### PR TITLE
issues comment API client

### PR DESCRIPTION
**Pull request by iwanbk**
Issues comment API client library, related to : 

- https://github.com/gogits/gogs/issues/1692#issuecomment-206590786
- https://github.com/gogits/go-gogs-client/issues/25

API docs proposal will be submitted in server side PR

### CODE REVIEW

**Comment by Unknwon** [comment]
Please signed the CLA.

**Comment by iwanbk** [comment]
@Unknwon done, just signed the CLA

**Comment by iwanbk** [comment]
@Unknwon any other things to do for this PR to be accepted?

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
