### PR TITLE
ListIssues func respect state option

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
@unknwon ping ;)

**Comment by 6543** [comment]
@unknwon can you please review this bugfix?

**Review by unknwon — APPROVED** [review]
Thanks! What happens if the `opt.State` is empty?

**Comment by 6543** [comment]
@unknwon as it is now ...

**Comment by unknwon** [comment]
Ah, right. Haha, merging!

**Pull request merged**
